apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: php-deployment
  namespace: demo-namespace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: sachinar/sample-phpapp:v1
        ports:
        - containerPort: 80
